### ISSUE TITLE
Larger buckets in chunk index

### ISSUE THREAD

**Issue by jml** [weaveworks/cortex#10]
_From @tomwilkie_

Should reduce index size, super important for scalability.

_Copied from original issue: tomwilkie/frankenstein#9_

**Comment by jml** [comment]
*From @jml*

@tomwilkie Do you have some idea for how much larger they should be, or thoughts on how to determine how much larger?

**Comment by jml** [comment]
*From @tomwilkie*

Chunk index 'big' bucket size mainly affects the number of range queries you need to do on query. Smaller buckets = more range queries = more dynamodb cost & slower queries.

OTOH larger buckets mean more chunks / bucket, which means more items returned in the range queries. Limit on dynamodb range queries is 25 items before you start paging. So we should look and see how many chunks / query we are getting, and tune that until it hits 25. I have a feeling it will be 24hrs...

**Comment by tomwilkie** [comment]
We need to gather stats on pages per query before deciding on this, but its looks like we are going toward bigger chunks, so 24hr buckets might be a good idea.

**Comment by tomwilkie** [comment]
Code is in, flag just needs deploying to dev and testing.

**Comment by tomwilkie** [comment]
Has been deployed to prod and will go live tomorrow.
