### ISSUE TITLE
Tune chunk size

### ISSUE THREAD

**Issue by jml** [weaveworks/cortex#11]
_From @tomwilkie_

Currently 10mins, should be 1hr.

_Copied from original issue: tomwilkie/frankenstein#10_

**Comment by jml** [comment]
*From @jml*

Why should it be 1hr?

**Comment by jml** [comment]
*From @tomwilkie*

We should investigate what the right number is, but the parameters are:
- data batched up in the ingesters is a risk of loss in event of machine failure.  we should bound this.
- chunks are 1kb, and making bigger chunks doesn't necessarily make things more efficient.  we should try and fill chunks as much as possible (something we already monitoring for).

Ticket should really say "max 1hr" to bound the loss, if that give good utilization

**Comment by jml** [comment]
This is possibly related to the dynamo errors we are seeing in #85

**Comment by juliusv** [comment]
Oh wow yeah, the default chunk max age of 10 minutes seems way too low. I'm wondering why we're still achieving such decent chunk utilization (`sum(cortex_ingester_chunk_utilization_sum) / sum(cortex_ingester_chunk_utilization_count)` is around `0.43`) with such a low max age. Under certain circumstances, chunks can last for hours or days, so maybe it's the frequent scraping plus noisiness of the data that makes the chunks fill up that fast. Still, I would set the max age to an hour or so (as you said, it depends a bit on our risk profile, of course).

**Comment by tomwilkie** [comment]
I suspect it can't flush chunks quickly enough, and therefore they are
getting more than 10mins worth of data.

**Comment by juliusv** [comment]
> I suspect it can't flush chunks quickly enough, and therefore they are getting more than 10mins worth of data.

At least the failures should not have a big effect because during normal operation, only ~4% of chunk puts fail (`sum(rate(cortex_ingester_chunk_store_failures_total[1m])) / sum(rate(cortex_ingester_chunk_utilization_count[1m]))` -> 0.043). Maybe general latency in non-failed puts delays things somewhat, but the effect cannot be huge, as `sum(cortex_ingester_memory_chunks) / sum(cortex_ingester_memory_series)` shows us that there's just 1.12 chunks per series in memory at a given time (there's always at least one open head chunk for active series).

**Comment by tomwilkie** [comment]
Actually make sense, since we're on doubledelta (not varbit).  So its about 3 bytes per sample, at 15s scrape interval == about 20mins per chunk.  With 10mins, you'd expect 50% utilisation.

**Comment by juliusv** [comment]
Hmm, how do you get to 20 mins per chunk at 15s scrape interval and 3.3 bytes per sample? 1024 / 3.3 = 310 samples per chunk, but 20 minutes of samples would only be 4 * 20 = 80 samples? So a chunk should be full after ~ 310 / 4 = 77 minutes. Or am I missing something stupid?

**Comment by tomwilkie** [comment]
Nope, I was being stupid.  I did 300/15 not 300*15.

**Comment by tomwilkie** [comment]
Okay, bit more progress: 99th percentil chunk "age" is 27mins on flush.  This could explain the higher utilisation.  Just added a dashboard for it, will link to it when it live.

**Comment by tomwilkie** [comment]
So, the question is why are some chunks 27mins old?

Thoughts:
- it takes 0.8s avg to flush a single chunk [0.07s s3](http://frontend.dev.weave.works/admin/prometheus/graph?g0.range_input=1h&g0.expr=sum(cortex_s3_request_duration_seconds_sum)+%2F+sum(cortex_s3_request_duration_seconds_count)&g0.tab=0) + [0.7s dynamo](http://frontend.dev.weave.works/admin/prometheus/graph?g0.range_input=1h&g0.expr=sum(cortex_dynamo_request_duration_seconds_sum)+%2F+sum(cortex_dynamo_request_duration_seconds_count)&g0.tab=0)
- we limit concurrent chunk flushes to 100
- we need to flush 20k chunks every 10mins
- means we should be able to flush all chunks in ~3mins.

**Comment by tomwilkie** [comment]
Except:
- we need to write to dynamo multiple times for each chunk (due to indexing)
- we batch dynamo write (currently doing about 200qps, and using about 600 capacities/s in dynamo, so batch size is 3?

**Comment by tomwilkie** [comment]
Average number of entries per chunk is 8.6 (here)[http://frontend.dev.weave.works/admin/prometheus/graph?g0.range_input=30m&g0.expr=sum(cortex_chunk_store_index_entries_per_chunk_sum%7Bjob%3D%22cortex%2Fingester%22%7D)+%2F+sum(cortex_chunk_store_index_entries_per_chunk_count%7Bjob%3D%22cortex%2Fingester%22%7D)&g0.tab=0]

And its no coincident that 8.6 * 3min is 27mins - which is the 99%ile chunk age...

**Comment by tomwilkie** [comment]
With the latest change, we may be writing chunks more than once.  Needs fixing.

**Comment by tomwilkie** [comment]
Set to 1hr and behaving as expected in #118
