### ISSUE TITLE
99th Chunk Age is BS

### ISSUE THREAD

**Issue by tomwilkie** [weaveworks/cortex#121]
<img width="561" alt="screen shot 2016-11-07 at 15 48 07" src="https://cloud.githubusercontent.com/assets/444037/20081016/c93a23d6-a501-11e6-84d3-60c206cc51b3.png">

**Comment by tomwilkie** [comment]
I suspect histogram buckets

**Comment by jml** [comment]
This might not be BS, it might be an actual representation of the distribution. It would be consistent with a very high outlying maximum, for example.

**Comment by tomwilkie** [comment]
I think it's BS, as with all my changes it hasn't wavered from 27mins. I
think it needs more investigation.

**Comment by jml** [comment]
>  I think it needs more investigation.

Me too.

**Comment by tomwilkie** [comment]
Also see https://github.com/weaveworks/monitoring/pull/41
