### ISSUE TITLE
Separate out ingester index?

### ISSUE THREAD

**Issue by jml** [weaveworks/cortex#13]
_From @tomwilkie_

To allow for non-metric-name queries, and improve load balancing in ingesters

_Copied from original issue: tomwilkie/frankenstein#12_

**Comment by tomwilkie** [comment]
The idea here is to use a different sharding scheme for the index (probably just userid) than the actual series data (recently switched to hash of all labels).  The idea being we could reduce the number of ingesters needed to be queried for any one query, whilst still having good load balancing.

But in hindsight I think just sharding both by all labels is good enough: even if the index is more focused, if data is spread evenly amongst all the ingesters, we'll have to touch them all on every query.

I suggest we close this.
