### ISSUE TITLE
Use packages, clean up code etc

### ISSUE THREAD

**Issue by jml** [weaveworks/cortex#16]
_From @tomwilkie_

_Copied from original issue: tomwilkie/frankenstein#15_

**Comment by jml** [comment]
*From @jml*

@tomwilkie This will need a better description if someone else can attempt it.

**Comment by jml** [comment]
*From @tomwilkie*

I guess we probably want a package for each component - ingestor, distributor, querier?

And by code cleaner I just mean removing TODOs, adding unit tests, improving code smells, better decoupling, be more stringent in code reviews.

**Comment by jml** [comment]
*From @tomwilkie*

OK. I suggest we make the package-per-component bit the thing for this ticket and do the other stuff incrementally as we make other changes.

**Comment by jml** [comment]
*From @tomwilkie*

Agreed!

**Comment by tomwilkie** [comment]
Status:
- the chunk store etc has been put in a separate package
- the ring & consul stuff is in a package

Todo:
- [ ] put distributor code in a package
- copy ingester code into here, in a new package (see #20)
- get the querier changes upstream, pipe through contexts etc - @juliusv is working on it - is there a issue for this?
