### ISSUE TITLE
Leaking gRPC clients

### ISSUE THREAD

**Issue by tomwilkie** [weaveworks/cortex#217]
When we rollout new ingesters, the distributor never stop the clients for the old ones, spamming the logs with:

```
2017/01/18 15:22:21 grpc: addrConn.resetTransport failed to create client transport: connection error: desc = "transport: dial tcp 10.244.254.81:9095: getsockopt: no route to host"; Reconnecting to {10.244.254.81:9095 <nil>}
2017/01/18 15:22:43 grpc: addrConn.resetTransport failed to create client transport: connection error: desc = "transport: dial tcp 10.244.253.93:9095: getsockopt: no route to host"; Reconnecting to {10.244.253.93:9095 <nil>}
2017/01/18 15:23:37 grpc: addrConn.resetTransport failed to create client transport: connection error: desc = "transport: dial tcp 10.244.204.160:9095: getsockopt: no route to host"; Reconnecting to {10.244.204.160:9095 <nil>}
```

**Comment by juliusv** [comment]
The ring doesn't explicitly track which ingesters have gone away, nor is there currently a suitable channel of communication between the distributor and the ring for that. Rather than changing those, what do you think about simply removing ingester clients that haven't been used for X seconds?

**Comment by tomwilkie** [comment]
> Rather than changing those, what do you think about simply removing ingester clients that haven't been used for X seconds?

Yup, sounds like a plan.  I think we'll need ref counts on the clients too, and we'll need to be careful around the locking as this bit is performance sensitive.

**Comment by juliusv** [comment]
Hm yeah, I'll have to look closer at that.

It could be even better to periodically call `ring.GetAll()` to see which ingesters should currently be there and delete the ones that aren't in the ring anymore. Then we don't need to track access times, only whether there's still a current request happening on one. Still needs to avoid races between `GetAll()` and the removal.

**Comment by juliusv** [comment]
Actually I'm not sure we need reference-counting. An ingester should only disappear from the ring when it's really gone, in which case it should be fine to assume that any connections to it are defunct anyways and can be closed. The one corner case is ingesters disappearing from the ring when they fail their heartbeat timeout. It's conceivable that they just fail to register with Consul, but are still up otherwise. However, any new queries or pushes to those ingesters would still fail then, as they wouldn't be returned by the ring anymore, so in that situation it shouldn't make much of a difference anymore if a few currently running RPCs against them are terminated as well.

**Comment by tomwilkie** [comment]
I was just trying to avoid us closing a in-use client.  Consider a write to
a ingester that then exists.  After the ingester removed itself from the
ring, but before the write returns, theres a window where we might close
the client with an outstanding request.

I guess this race exists anyway (as we don't do any 2pc when ingesters
shutdown) and replication should be able to deal with loosing the
occasional write.  So yeah, simpler is better.

**Comment by juliusv** [comment]
We include `IngesterState_LEAVING` ingesters in `ring.GetAll()` (which makes sense for queries), and ingesters only fully remove themselves from the ring once they've finished handling existing writes. So that should be all good?

**Comment by tomwilkie** [comment]
Yeah, until we get round to thinking about joining...
