### ISSUE TITLE
Incorrect `==` and `=~` label matching behavior for empty label values

### ISSUE THREAD

**Issue by juliusv** [weaveworks/cortex#220]
In Prometheus, a non-existent label `foo` is equivalent to an empty label `foo=""` (in fact, labels with empty values are removed before a series is stored). That is in Prometheus, `{foo=""}` returns all series with no foo label, as does `{foo=~""}`. Cortex currently returns no series for these, because it actually looks for a `foo` label to be present.

I stumbled over this when looking at https://github.com/weaveworks/cortex/pull/191.

**Comment by tomwilkie** [comment]
Whoops!  Good to know.  Should be an easy fix.

**Comment by tomwilkie** [comment]
With the chunk index we use, we don't have a way of querying for things that don't have a label - best I can think of is looking for things that satisfy other matchers, then filtering to remove those with the specified label.
