### ISSUE TITLE
remove the ui folder & codegen

### ISSUE THREAD

**Issue by juliusv** [weaveworks/cortex#223]
...once the new cortex-ui is ready.

**Comment by rade** [comment]
What exactly is meant by "the new cortex ui"? The recent innovation, that is live on Weave Cloud?

**Comment by juliusv** [comment]
@rade Good question, I just converted @tomwilkie's two text notes from the project board to issues by clicking "convert to issue" :) I also added the other two missing issues to the project board.

**Comment by rade** [comment]
@juliusv yes, I figured that. Thank you! Hopefully Tom and David can clarify.

**Comment by tomwilkie** [comment]
> What exactly is meant by "the new cortex ui"? The recent innovation, that is live on Weave Cloud? cc @davkal @tomwilkie

Yes.
