### ISSUE TITLE
Concurrent map read/write crash in distributor

### ISSUE THREAD

**Issue by juliusv** [weaveworks/cortex#248]
See https://gist.githubusercontent.com/juliusv/4566ce03ad1af97b7ab42ae971267bf4/raw/11cf46ca555d39c3fe1254c5030066d8c6c0173d/distributor_crash.txt

The crash happens in this line: https://github.com/weaveworks/cortex/blob/master/vendor/github.com/grpc-ecosystem/grpc-opentracing/go/otgrpc/shared.go#L29

**Comment by tomwilkie** [comment]
Upstream issue: https://github.com/grpc-ecosystem/grpc-opentracing/issues/12 and PR: https://github.com/grpc-ecosystem/grpc-opentracing/pull/13

**Comment by tomwilkie** [comment]
Let not close until the fix is merged upstream and we're back vendoring it.

**Comment by tomwilkie** [comment]
Upstream merged, going to update cortex.
