### ISSUE TITLE
Figure out good series-per-metric limit

### ISSUE THREAD

**Issue by juliusv** [weaveworks/cortex#277]
See https://github.com/weaveworks/cortex/pull/276#discussion_r99879908

**Comment by tomwilkie** [comment]
50k is the default. We're running at 200k by default and 500k for some users at Grafana Labs.  Write path works fine with the sharding improvements, and the read path is getting better.  

Given this is tuneable, I see no reason to leave this issue open?  Perhaps making it tuneable per user would be nice, but thats a separate issue.

**Comment by juliusv** [comment]
Yeah, I'm not even sure back then this was suggested as a code change or for someone at Weaveworks to think more about what the right limit for their context would be :) Fine by me to close it.

**Comment by bboreham** [comment]
Tuneable per user seems like the future for me. 

Also some way to find out who’s got high-cardinality but under the limit.
