### ISSUE TITLE
Running predefined reports displays "no datapoints" even though data is displayed

### ISSUE THREAD

**Issue by abuehrle** [weaveworks/cortex#293]
Setup: Kubernetes, Sockshop, on Ubuntu 10.06

When I run a one of the reports in the Prometheus System Queries section, they are all returning "No data points", yet data is being returned.  I am not seeing the same issue in the Kubernetes section. 

<img width="880" alt="screen shot 2017-02-14 at 7 55 45 am" src="https://cloud.githubusercontent.com/assets/13420383/22931786/9756e28c-f28b-11e6-950a-ccde5053f42f.png">

**Comment by abuehrle** [comment]
I see what's happening here.  There are no datapoints, this is true, but the screen is not refreshing from any prior graph that was displayed.

**Comment by tomwilkie** [comment]
Could you file this in service-ui if its a UI bug please?

**Comment by abuehrle** [comment]
moved
