### ISSUE TITLE
shift+enter auto-completes and not executes

### ISSUE THREAD

**Issue by BenHall** [weaveworks/cortex#302]
When I'm at the end of the line, I can use shift-enter to execute a query in the Prom Notebook.

However, if I'm mid-query it auto completes

sum(rate(who_lives_where_request&lt;cursor-here&gt;_count[10s]))

shift-enter causes it to become

sum(rate(who_lives_where_requestwho_lives_where_request_count_count[10s]))

**Comment by tomwilkie** [comment]
Thanks for the report Ben; David (cc'd) is the man for the job.
