### ISSUE TITLE
query returns more timeseries than selected

### ISSUE THREAD

**Issue by rade** [weaveworks/cortex#303]
In https://frontend.dev.weave.works/prom/proud-wind-05/wrapper I entered
```
irate(node_cpu{job="monitoring/prom-node-exporter",mode="idle"}[1m])
```
in our expression browser, and some of the returned data is for modes other than "idle", e.g. "user" and "system".
![screenshot_2017-02-26_14-29-16](https://cloud.githubusercontent.com/assets/109109/23340566/708bcf9c-fc30-11e6-883f-64dcfcd08167.png)

Entering the same query into the dev prometheus, only produces data for "idle", as expected.

**Comment by rade** [comment]
Here's another query that shows more clearly that something is amiss:
![screenshot_2017-02-26_14-43-02](https://cloud.githubusercontent.com/assets/109109/23340658/16b4c5bc-fc32-11e6-909f-e220b0c27e1b.png)

Again, entering this in plain prom only produces data for mode="idle", as expected.

**Comment by rade** [comment]
@tomwilkie says "easy fix"

**Comment by rade** [comment]
Tom says this is only an issue in dev, not in prod. And indeed running the query myself in prod I do not see modes other than 'idle' in the result.

**Comment by tomwilkie** [comment]
Problem is probably with new v5 schema, which writes raneg values of the form [chunk end, label value, chunk id].  We then do range queries for [query start, label value, *] -> *, which of course will return chunks for other label values.

There is a test in https://github.com/weaveworks/cortex/blob/master/chunk/chunk_store.go#L413 that checks and drops items which don't match the matcher, which I thought would catch this.  But it isn't, and I don't know why.

**Comment by tomwilkie** [comment]
Still seeing this:

<img width="948" alt="screen shot 2017-03-13 at 18 51 40" src="https://cloud.githubusercontent.com/assets/444037/23870403/35d72cee-081e-11e7-9f6b-04f008ce008b.png">

**Comment by tomwilkie** [comment]
Weird: I don't get the wrong ones when I remove the functions:

<img width="920" alt="screen shot 2017-03-13 at 19 10 45" src="https://cloud.githubusercontent.com/assets/444037/23871087/e2e212f8-0820-11e7-9d9f-e463bdee2f6f.png">

**Comment by tomwilkie** [comment]
Oh yes I do - false alarm.

**Comment by tomwilkie** [comment]
I commented out the memcache calls and I don't get the errors any more.

**Comment by tomwilkie** [comment]
Things I'm going to try:
- [ ] check memcache keys well-formed, fit within length restrictions
- [ ] think about if there is a memcache keys collision, add more uniqueness
- [ ] add the chunk ID to the chunks header, have a check that we get the right chunks
- [ ] add a hash of the chunk contents to the key, check we receive the right chunk on queries.
- [ ] add unit tests to the memcache client code

**Comment by tomwilkie** [comment]
Memcache keys are limited to 250 bytes.

Out current memcache key is `<userid>/<fingerprint>:<chunk start>:<chunk end>`, all 64bit ints.

So may length is about 90bytes.

Fingerprints could clash between different ingesters, even if there is a small chance.  So will add ingester ID.

**Comment by Bplotka** [comment]
I had the same issue with single ingester, so not sure if ingesterID will help (with https://github.com/weaveworks/cortex/issues/304) issue

**Comment by tomwilkie** [comment]
Good point.
