### ISSUE TITLE
Cortex reports "per-metric series limit exceeded" as 500

### ISSUE THREAD

**Issue by tomwilkie** [weaveworks/cortex#314]
<img width="1266" alt="screen shot 2017-03-06 at 11 19 39" src="https://cloud.githubusercontent.com/assets/444037/23608307/af60c2be-0260-11e7-8e60-50f6131c18c1.png">

**Comment by juliusv** [comment]
It's returning `507 Insufficient Storage` to the retrieval layer. Yeah, that probably should be a `4xx`, not a `5xx`? There's no really fitting `4xx` code though. We could reuse `429 Too Many Requests`, which we already use for ingestion rate limiting?

**Comment by juliusv** [comment]
Or `413 Payload Too Large` - also not super fitting though.

**Comment by tomwilkie** [comment]
429 sounds good.  5xx trigger alerts for us.
