### ISSUE TITLE
ValidationErrors while shutting down ingester

### ISSUE THREAD

**Issue by jml** [weaveworks/cortex#316]
When shutting down an ingester for routine maintenance, I noticed an increase in chunk store flush failures due to "ValidationException":

<img width="1039" alt="screen shot 2017-03-07 at 12 10 55" src="https://cloud.githubusercontent.com/assets/125674/23655900/2beb0186-032f-11e7-85ce-53a6158992ea.png">

Also, the series queue flush length stalled, rather than steadily decreased

<img width="1044" alt="screen shot 2017-03-07 at 12 11 36" src="https://cloud.githubusercontent.com/assets/125674/23655920/49952f90-032f-11e7-8821-a5fd51b0f962.png">

Checking the logs, I saw lots of errors like these:

```
request id: DSCAO85A35JL2HLMUCPRPOMTSJVV4KQNSO5AEMVJF66Q9ASUAAJG" source="ingester.go:516"
time="2017-03-07T12:06:28Z" level=error msg="Failed to flush user: ValidationException: One or more parameter values were invalid: Aggregated size of all range keys has exceeded the size limit of 1024 bytes\n\tstatus code: 400, request id: O3EBMNFFUCSU252KDI1TKHTE9NVV4KQNSO5AEMVJF66Q9ASUAAJG"
```

This represents a serious problem, as we cannot shut down these ingesters cleanly.

**Comment by jml** [comment]
Also, 

- we don't know what data is failing to flush
- possible that we are retrying incorrectly (the logs are being spammed with the above message quite a lot, but maybe that's just because there are a lot of chunks to flush)

**Comment by jml** [comment]
We _are_ retrying incorrectly, at least by my reading of the code:

https://github.com/weaveworks/cortex/blob/master/ingester/ingester.go#L538-L544
– [version we are running](https://github.com/weaveworks/cortex/blob/fcbaa93/ingester/ingester.go#L512-L518)

We should:
- discriminate as to whether the error is recoverable or not (provision throughput exceeded can be retried, validation cannot)
- log the user id

**Comment by tomwilkie** [comment]
Yeah, @juliusv + I discussed having a different approach in https://github.com/weaveworks/cortex/pull/234

ProvisionedThroughputExceeded errors are retries at the next layer down.  At this level, its quite hard to work out what is a transient error and what can be retried. 

We should probably not loop on failing operations, but rather move them to the back of the queue and continue flushing other.  That way we can maximise how much we can flush.

**Comment by tomwilkie** [comment]
To address the ValidationException, I propose we move the label value out of the range key and into another field in dynamodb.

Downside is this will make queries of the for `{foo="bar"}` perform the same as `{foo=~"bar"}`.  But that pretty much the case with v5 schema anyway, as the first field in the range key is a timestamp now.  

Alternatively, we could hash the values and put them in the key.  This is a possible optimisation for later, as it will double the number of writes needed (but make queries _much_ faster).
