### ISSUE TITLE
Connection/FD leak on ingester when it cannot access S3

### ISSUE THREAD

**Issue by Bplotka** [weaveworks/cortex#319]
Between Monday and Tuesday I accident revoked access to S3, so Cortex on my cluster could not make any request to S3. (Dynamo was fine)

Apart of the facts that:
* there was not any failure metric for s3 request (will do that in next PR)
* actual metrics for `chunk age` , `chunkLength` and `chunkUtilization` were reported before actual request, so the reported data was not true:
```
func (i *Ingester) flushChunks(ctx context.Context, fp model.Fingerprint, metric model.Metric, chunkDescs []*desc) error {
	wireChunks := make([]cortex_chunk.Chunk, 0, len(chunkDescs))
	for _, chunkDesc := range chunkDescs {
		i.chunkUtilization.Observe(chunkDesc.C.Utilization())
		i.chunkLength.Observe(float64(chunkDesc.C.Len()))
		i.chunkAge.Observe(model.Now().Sub(chunkDesc.FirstTime).Seconds())
		wireChunks = append(wireChunks, cortex_chunk.NewChunk(fp, metric, chunkDesc.C, chunkDesc.FirstTime, chunkDesc.LastTime))
	}
	return i.chunkStore.Put(ctx, wireChunks)
}
``` 
(Will fill separate issue for that)

I found that there might be some open file descriptors leak (probable because of not closed connections) because of that:
![image](https://cloud.githubusercontent.com/assets/6950331/23714769/53d508ec-0422-11e7-8985-2c2083db91dd.png)

Will investigate that more soon, but if someone has free cycles.. feel free to fix that. (:

**Comment by tomwilkie** [comment]
> there was not any failure metric for s3 request (will do that in next PR)

`cortex_s3_request_duration_seconds_count{status_code="500"}`

https://github.com/weaveworks/cortex/blob/master/chunk/chunk_store.go#L29

> actual metrics for chunk age , chunkLength and chunkUtilization were reported before actual request, so the reported data was not true:

Good catch!  We should only report this on success.

> I found that there might be some open file descriptors leak (probable because of not closed connections)

I had kinda hopes the S3 library would deal with this...  looking into it.

**Comment by Bplotka** [comment]
Ah you are right about s3 failure metric.. Sorry for that. I have seen:
```
dynamoFailures = prometheus.NewCounterVec(prometheus.CounterOpts{
		Namespace: "cortex",
		Name:      "dynamo_failures_total",
		Help:      "The total number of errors while storing chunks to the chunk store.",
	}, []string{tableNameLabel, errorReasonLabel})
```
And I have not seen anything like that for S3. So ok, it 's not needed, I can have failure rate from:
`sum(irate(cortex_s3_request_duration_seconds_count{status_code!="200"}[1m])) by (job, status_code, operation)`

> I had kinda hopes the S3 library would deal with this... looking into it.
I don't think we can close anything from SDK, so either they have a bug in Go SDK or there is something else accumulating open file descriptors on ingester (goroutine leak?). Would love to see number of go routines or pprof, but did not snap that.

Maybe `body, err := chunk.reader()` needs to be closed by us in error case? Just guessing now (:

**Comment by tomwilkie** [comment]
> Maybe body, err := chunk.reader() needs to be closed by us in error case? Just guessing now (:

I don't think its that - thats just a `MultiReadSeeker` underneath, no FDs involved.

I'll try revoking access to S3 and see what happens.

**Comment by tomwilkie** [comment]
We're moving away for S3 for chunk storage, so I'm going to close this issue.
