### ISSUE TITLE
Metrics are reported before actual action. (e.g PUT request to S3)

### ISSUE THREAD

**Issue by Bplotka** [weaveworks/cortex#333]
As a result metrics can be misleading when action did not complete (e.g failed request to S3)

Spotted in ingester e.g here: https://github.com/weaveworks/cortex/blob/master/ingester/ingester.go#L607
Not yet sure if somewhere else as well.

Mentioned that already here: https://github.com/weaveworks/cortex/issues/319

**Comment by tomwilkie** [comment]
@Bplotka good catch.  Would welcome a PR to fix this...

**Comment by Bplotka** [comment]
I know I know ^^ 
Worst user ever.. only complaining and not fixing... Will do my best to catch up on this!  

Fix for this issue: https://github.com/weaveworks/cortex/pull/336

**Comment by Bplotka** [comment]
Fix, merged.
