### ISSUE TITLE
Display per-user metrics metadata

### ISSUE THREAD

**Issue by juliusv** [weaveworks/cortex#35]
To give users some amount of initial feebback, it'd be great for Cortex to show some per-user stats in the user's Cortex dashboard:

- number of metrics
- number of time series
- samples/s

This will require adding backend support for getting those stats from the ingesters. Probably the distributor will have to query all ingesters for their current metadata for a given user and then aggregate those stats for the UI.

**Comment by rade** [comment]
[design](https://docs.google.com/a/weave.works/presentation/d/1lUL9jAXx8Hi_Fjql9dGB3x7LWnWi4mo18W19hVmcpw4/edit?usp=sharing)

**Comment by juliusv** [comment]
See also https://github.com/weaveworks/service/issues/844#issuecomment-253814894 about implementing the minimal version of UI feedback without requiring any backend changes.
