### ISSUE TITLE
Swtich to varbit has led to 10% of batch write failing to ingesters

### ISSUE THREAD

**Issue by tomwilkie** [weaveworks/cortex#355]
Distributors still at 100% success, probably due to the quorum logic.

Error is caused by us writing values in the past (see https://github.com/prometheus/prometheus/blob/master/storage/local/chunk/varbit.go#L554), but we check for that in the series.go (https://github.com/weaveworks/cortex/blob/master/ingester/series.go#L69)

Could be a bug in the handling of the LastTime propagation in the transfer code.

**Comment by tomwilkie** [comment]
<img width="629" alt="screen shot 2017-03-17 at 11 38 34" src="https://cloud.githubusercontent.com/assets/444037/24041634/4a88d684-0b06-11e7-9185-58e47d240696.png">

**Comment by juliusv** [comment]
While taking a look at this, I found that https://github.com/weaveworks/cortex/commit/05b931b1319876476f0daaabf1f0cca8ee798039#diff-7ff2202450a7e6aef5ad5bc310682570L144 removed the setting of the last timestamp and last sample value. But that's what we use to check monotonicity / noop appends *before* we add something to a chunk. Seems like a likely culprit?

**Comment by juliusv** [comment]
Also, we don't initialize the last sample value upon transfer.

I'm going to try a tentative fix that we can try out in dev.
