### ISSUE TITLE
RBAC permissions required for Prometheus and node exporter for Kubernetes 1.6

### ISSUE THREAD

**Issue by errordeveloper** [weaveworks/cortex#366]
Essentially I just need a list of permissions that is required for Prometheus and node exporter to function, like [what we have for Net](https://github.com/weaveworks/weave/blob/8862d4f76e8ccc208d35b05b25f95f465edb7fc6/prog/weave-kube/weave-daemonset-k8s-1.6.yaml).

**Comment by tomwilkie** [comment]
Closing in favour of #392, as there is more info there.
