### ISSUE TITLE
Kubernetes 1.6 support?

### ISSUE THREAD

**Issue by BenHall** [weaveworks/cortex#392]
Does Cortex support Kubernetes 1.6? I'm only seeing one agent/node deployed onto a two node cluster and I seem to be getting errors related to RBAC in the agent logs. Related to https://github.com/weaveworks/cortex/issues/366 ?

Here are some details:

```
weave-cortex-agent logs:

time="2017-04-07T17:34:40Z" level=error msg="github.com/prometheus/prometheus/vendor/k8s.io/client-go/1.5/tools/cache/reflector.go:109: Failed to list
 *v1.Pod: the server does not allow access to the requested resource (get pods)" component="kube_client_runtime" source="kubernetes.go:50"
```

Weave Cloud says
```
NO PROMETHEUS FOUND
INSTANCES:JOBS:
```

```
$ kubectl get nodes
NAME      STATUS    AGE       VERSION
master    Ready     8m        v1.6.1
node      Ready     7m        v1.6.1

$ kubectl get pods -n kube-system -l weave-cloud-component=cortex
NAME                                  READY     STATUS    RESTARTS   AGE
weave-cortex-agent-1779788556-m5h1b   1/1       Running   0          5m
weave-cortex-node-exporter-013fx      1/1       Running   0          6m
```

**Comment by tomwilkie** [comment]
@juliusv hit similar problems - it's not cortex specific, but in general
Prometheus is having problems with k8s 1.6. @errordeveloper, is this
something you can help with?

**Comment by juliusv** [comment]
Yeah, I cheated in the end because I just had a local test Kubernetes cluster, so I just created a cluster role binding that allows everyone to access anything:

```
kubectl create clusterrolebinding permissive-binding \
  --clusterrole=cluster-admin \
  --user=admin \
  --user=kubelet \
  --group=system:serviceaccounts
```

I got this from the very bottom of https://kubernetes.io/docs/admin/authorization/rbac/. See the warning there: "WARNING: The following policy allows ALL service accounts to act as cluster administrators. Any application running in a container receives service account credentials automatically, and could perform any action against the API, including viewing secrets and modifying permissions. This is not a recommended policy."

**Comment by BenHall** [comment]
@juliusv Thanks! That's useful in the short-term

**Comment by rade** [comment]
@errordeveloper ping

**Comment by matthiasr** [comment]
Cross-linking from [this thread](https://groups.google.com/d/msgid/prometheus-users/e2c20f10-d2a9-4bc3-89bc-c09f6d788961%40googlegroups.com), the necessary roles are documented in the [Prometheus operator docs](https://github.com/coreos/prometheus-operator/blob/master/Documentation/rbac.md#prometheus-rbac).

**Comment by errordeveloper** [comment]
We have permissive settings in launch generator at the moment, and most things appear to work, except for node exporter getting a 403 from kubelet (`<host>:10250/metrics`). I've checked node exporter repo, but couldn't find any obvious references to either RBAC or 1.6... I wonder how it makes the request? ...is it just a basic HTTP GET or it's able to do an auth dance using the service account I just need to configure it somehow?

**Comment by errordeveloper** [comment]
I've posted on the mailing list thread as well, let's see if any clarification comes from there...

**Comment by matthiasr** [comment]
See prometheus/prometheus#2606 and prometheus/prometheus#2641 for a working example. Please comment on the latter if it's unclear how to adapt it.
