### ISSUE TITLE
incorrect results from recording rule queries in dev

### ISSUE THREAD

**Issue by rade** [weaveworks/cortex#394]
Querying for `job:scope_request_duration_seconds:99quantile{job="scope/collection"} * 1e3` for dev shows incorrect results in cortex dev, i.e. https://frontend.dev.weave.works/prom/proud-wind-05:
![screenshot from 2017-04-12 02-04-38](https://cloud.githubusercontent.com/assets/109109/24936842/a013e71a-1f24-11e7-8045-501b15189321.png)

The correct result is shown when expanding the recording rule
![screenshot from 2017-04-12 02-04-53](https://cloud.githubusercontent.com/assets/109109/24936854/ae984a88-1f24-11e7-8ade-2111f3cd02de.png)
as confirmed by querying the recording rule in the prod cortex looking at dev
![screenshot from 2017-04-12 02-05-18](https://cloud.githubusercontent.com/assets/109109/24936874/cd5e1b6e-1f24-11e7-9883-873d5ddf6a9f.png)
and directly in the dev prometheus
![screenshot from 2017-04-12 02-08-20](https://cloud.githubusercontent.com/assets/109109/24936927/f2711708-1f24-11e7-8846-8ad20548e09b.png)

**Comment by bboreham** [comment]
I suspect this could have been caused by the issue that #492 fixed.  The graphs between recording-rule and exploded query look the same to me right now; @rade could you check again please.

**Comment by bboreham** [comment]
@rade bump

**Comment by rade** [comment]
If you think this is fixed, close it.
