### ISSUE TITLE
Recording rules

### ISSUE THREAD

**Issue by jml** [weaveworks/cortex#4]
_From @tomwilkie_

Need to support them...

_Copied from original issue: tomwilkie/frankenstein#3_

**Comment by tomwilkie** [comment]
@jml any progress on this?  I think this is next most important thing, and I'd like to get this in before optimising queries (so I have some load to optimise against).

**Comment by jml** [comment]
Last week or the week before I merged some refactoring PRs which were part of getting this done (we need to be able to execute queries). Keen to get back on it.

**Comment by rade** [comment]
What is left to do here?

**Comment by jml** [comment]
Roll out to prod

**Comment by jml** [comment]
Deployed & working.
