### ISSUE TITLE
Return key to regenerate graph only works after double-tap when cursor is not at the end of the query field

### ISSUE THREAD

**Issue by paulbellamy** [weaveworks/cortex#419]
Steps to reproduce:

1. Enter and run a query in a notebook (e.g. `sum(rate(microservices_demo_user_request_count[5m])) by (name)`)
1. Press enter
1. Note the query runs as a graph
1. Move cursor back and edit the query, leaving your cursor in the middle (e.g. change `name` to `method`)
1. Press enter
1. Note, the graph has not updated
1. Press enter again
1. Note, the graph has now updated.

Expected behaviour:

The graph should update when I press enter the first time, even when not at the end of the query.

**Comment by tomwilkie** [comment]
Thanks Paul; this is a known issue (weaveworks/service-ui#545), I'll try and bubble it up with @davkal.

**Comment by jml** [comment]
This issue was moved to weaveworks/service-ui#789
