### ISSUE TITLE
In-browser chrome pop-up notifications as an alert-route

### ISSUE THREAD

**Issue by paulbellamy** [weaveworks/cortex#420]
An easy default alert route, for users to try stuff out without necessarily having slack/email set up.

**Comment by tomwilkie** [comment]
Not a bad idea Paul!  Not too sure how chrome push works though, will need to read:

https://developers.google.com/web/fundamentals/engage-and-retain/push-notifications/

**Comment by rade** [comment]
> Not a bad idea Paul!

Indeed. Not just for cortex either. cc @pidster

**Comment by tomwilkie** [comment]
We could add support to alert manager in general - the web push API seems standardised:

https://tools.ietf.org/html/draft-ietf-webpush-protocol-12

**Comment by jml** [comment]
This issue was moved to weaveworks/service-ui#788
