### ISSUE TITLE
Notebook titles become corrupted when creating and switching between multiple notebooks

### ISSUE THREAD

**Issue by paulbellamy** [weaveworks/cortex#422]
Steps to reproduce:

1. Create one notebook `notebook1`
1. Create another notebook `notebook2`
1. Switch back and forth between the notebooks
1. Note that both notebooks are now named `notebook1`
1. Refresh the page, and note the notebook names persist incorrectly

Expected behaviour:

Multiple notebooks do not enforce their names on each other.

**Comment by tomwilkie** [comment]
I suspect this is going to go away with @aaron7's server-side persistence of notebooks.  @aaron7 is that ready to go out to prod?

**Comment by aaron7** [comment]
The frontend PR is still in review. It should go out to dev by the end of today and will go out to prod by the end of the week (after further testing).

**Comment by tomwilkie** [comment]
Thanks @aaron7.  Do you know whether it will fix this issue?

**Comment by aaron7** [comment]
Yes, this should be fixed by shareable notebooks as we have changed the way auto save works (i.e. removed it for now).

**Comment by jml** [comment]
This issue was moved to weaveworks/service-ui#786
