### ISSUE TITLE
Graph titles and queries are numbered separately in notebooks

### ISSUE THREAD

**Issue by paulbellamy** [weaveworks/cortex#423]
![screen shot 2017-05-17 at 10 40 06](https://cloud.githubusercontent.com/assets/250199/26148022/3ef2f55e-3aed-11e7-8a26-88b9a5bbeaaa.png)

Note, the title is `3`, then the query is `4`, but they are part of the same thing.

**Comment by jml** [comment]
This issue was moved to weaveworks/service-ui#785
