### ISSUE TITLE
Chunk Store should index series, not chunks

### ISSUE THREAD

**Issue by tomwilkie** [weaveworks/cortex#433]
Discussed with @aaron7, our index should be over series, not chunks.  This will enable lazily loading of chunk data in the future.

Indexes should be:
- userid:day -> series id -> label set
- userid:day:metric_name -> series id -> label set
- userid:day:metric_name:label_name -> #(label_value) : series_id -> (label_value, label_set)
- userid:day:series_id -> chunk_id -> chunk

**Comment by bboreham** [comment]
What do the two “->”s mean?

Where would the time appear?

**Comment by tomwilkie** [comment]
> What do the two “->”s mean?

Just shorthand for "maps to".  I think of the external storage as a set of nested, some times ordered, dictionaries.  So a -> b -> c means a is the row key, b is the column key and c is the value.

> Where would the time appear?

Dirty little secrete: time doesn't actually appear that much in the index.  There is the day (sometime called the 'big bucket') in the row key, then there is the chunk end time optimisation in the chunk id.

When we do this, we could change the 'series index' (last bullet) to sort chunks by start time, to enable the streaming unions and intersections.  We would lose some of the optimisations for "the last hour" style queries, but moving the ingester to TSDB will make those redundant anyway.

**Comment by bboreham** [comment]
For my own clarity, I was missing the point that chunk_id includes the time.

**Comment by bboreham** [comment]
Puzzled by your third bullet:

* userid:day:metric_name:label_name -> #(label_value) : series_id -> (label_value, label_set)

Let's see how much of my interpretation is correct:
- The label value is hashed to avoid excessively long or confusing strings.
- Series_id is concatenated so the range keys form a multi-valued set.
- The un-hashed label_value is there to resolve hash collisions.

What is label_set doing?  I can get that from the index in your first bullet, or from the chunks like we do today.  Perhaps, given multiple matchers, you look up one via the index then run the others over the label_sets ?  If so, label_value seems redundant as it is included in label_set.
