### ISSUE TITLE
Setting up dev environment

### ISSUE THREAD

**Issue by jsloyer** [weaveworks/cortex#470]
Hello, i am trying to setup the dev environment for cortex and running into issues... there is a reference in the ruler yaml to [http://configs.default.svc.cluster.local:80](https://github.com/weaveworks/cortex/blob/master/k8s/ruler-dep.yaml#L20), i don't see a reference to anything that actually deploys that service, how do i get that deployed?

**Comment by tomwilkie** [comment]
Ah good call that yaml is missing. I'll put something together on Monday if
that's okay? Otherwise the images is called weaveworks/cortex-config, it
needs a Postgres db, and the flags are described by --help.
