### ISSUE TITLE
Queries that range into the future result in table resource not found errors

### ISSUE THREAD

**Issue by awh** [weaveworks/cortex#472]
When using Grafana backed by Cortex, choosing the 'This Month' time range results in all graphs failing to render with the following error:

![screenshot from 2017-06-28 15-31-16](https://user-images.githubusercontent.com/1504438/27642554-1032d860-5c17-11e7-802c-eb696bbcf02b.png)

Presumably because the periodic tables for future weeks have not yet been created in dynamoDB.

Queries that range into the future should return no data rather than this error.

**Comment by tomwilkie** [comment]
Whoops! That should be an easy fix.

**Comment by awh** [comment]
PRs welcome :smile:
