### ISSUE TITLE
Potentially replace parts of Cortex's remote querying code with upstream code once it exists

### ISSUE THREAD

**Issue by jml** [weaveworks/cortex#5]
_From @tomwilkie_

Could probably also be upstreamed.

_Copied from original issue: tomwilkie/frankenstein#4_

**Comment by juliusv** [comment]
From email:

>> @rade:
>> Is this remote read-back feature what https://github.com/weaveworks/cortex/issues/5 is about? I thought it was but the issue is confusingly (to me) described as "remote query API" when querying cortex remotely is already possible today. So could somebody please add some clarification to that issue, one way or the other.
>
> @juliusv:
> I *think* that issue was more motivated by trying to upstream some of our own remote querying code so that we wouldn't have to maintain it ourselves. But it's strongly related to what would be needed upstream.

I'm going to create another issue for general remote queryability through Prometheus and rename this one.

**Comment by juliusv** [comment]
Ok with me.
