### ISSUE TITLE
Alerting

### ISSUE THREAD

**Issue by jml** [weaveworks/cortex#50]
When I've shown our hosted Prometheus stuff to people at conferences, they almost immediately ask about alerting, and being able to define custom alerts. We should implement that. 

Design doc: https://docs.google.com/a/weave.works/document/d/1ds8-9s3jj-m4r0ZXTBrbRfyBhRaquwI-oUxiuc3CNvc/edit?usp=drive_web

TODO before KubeCon:
- [x] Single tenant ruler -> alertmanager setup
- [x] Add user ID header to rule -> alertmanager RPCs
- [x] Make alert manager understand user ID - make it multitenant
- [x] Store per tenant alert manager config in config service (see https://github.com/weaveworks/service-ui/issues/301) (davkal)
- [x] backend validation features for AM config editing UI (see https://github.com/weaveworks/service-ui/issues/301) (julius, jml)
- [x] Actually try out HA mode (jml)
- [ ] Better metrics (merge / register the metrics from multiple AM user instances) (julius)
- [x] Ruler notifier actually sending multitenant requests

TODO later:
- [ ] Figure out Scale Up story for alert manager
- [ ] Notification templating support
- [ ] Persist silences & notification logs better
- [ ] Figure out how to show user Alertmanager-related errors (like failling to send a notification to Slack etc.)
- [ ] Do synchronous config applications (AM, rules) and show errors to users right away?

**Comment by jml** [comment]
From Slack, still to be done:

- [ ] better metrics
- [ ] notification templating support
- [ ] ruler notifier actually sending multitenant requests
- [ ] actually trying out HA mode

**Comment by jml** [comment]
#301 also adds:

- [ ] persist silences & notification logs

**Comment by juliusv** [comment]
@jml I'll add those to the top list so we have it all together, plus some more.

**Comment by jml** [comment]
HA mode links:
- https://coreos.com/blog/the-prometheus-operator.html
- https://github.com/coreos/prometheus-operator

**Comment by jml** [comment]
@juliusv Can you please link to the upstream work for merging metrics?

**Comment by bboreham** [comment]
I believe this one is done:
* [x] Do synchronous config applications (AM, rules) and show errors to users right away?
