### ISSUE TITLE
"now-7d" queries from grafana return partial data

### ISSUE THREAD

**Issue by rade** [weaveworks/cortex#503]
When looking at [some dashboards](https://frontend.dev.weave.works/admin/prod-grafana/dashboard/file/services.json?refresh=10s&orgId=1&from=now-7d%2Fd&to=now-7d%2Fd) at "This day last week" ("now-7d"), sometimes partial data or "No data points" is displayed. Here's an example:
![screenshot from 2017-07-13 10-29-07](https://user-images.githubusercontent.com/109109/28159910-770befd6-67b6-11e7-8f17-feaeabc0db22.png)
and here is the same range from a the standalone prometheus
![screenshot from 2017-07-13 10-34-17](https://user-images.githubusercontent.com/109109/28160051-edb6103a-67b6-11e7-900e-da918de683df.png)

Furthermore, the display is unstable, fluctuating between showing some (different) data, no data, or all data.

**Comment by leth** [comment]
If you refresh the graph does it sometimes show full data, and sometimes only partial?

**Comment by rade** [comment]
it's grafana, so the graph refreshes every few seconds. Yes, very occasionally it shows all data. Most of the times its seemingly random fragments or no data.

**Comment by aaron7** [comment]
This issue was moved to weaveworks/service-conf#969
