### ISSUE TITLE
Custom dashboards

### ISSUE THREAD

**Issue by jml** [weaveworks/cortex#51]
When I've shown our Prometheus functionality to people at conferences, they have asked about custom dashboards. Specifically, they've asked about:
- using grafana
- being able to provide their own data sources for grafana

The last case is from someone who is already running prometheus & grafana, but has their own extra proprietary data source that they use to add extra information to their graphs.

**Comment by tomwilkie** [comment]
This ticket doesn't belong here: Cortex is the backend, frontends should be handled elsewhere.
