### ISSUE TITLE
Add bazel test to circle CI

### ISSUE THREAD

**Issue by aaron7** [weaveworks/cortex#511]
To prevent https://github.com/weaveworks/cortex/issues/509

**Comment by tomwilkie** [comment]
Once https://github.com/bazelbuild/rules_go/issues/70 is fixed I'd really want to just move wholesale to bazel and remove out current Makefile.  I've been playing with it for other projects and its going to massively slash build times.

**Comment by tomwilkie** [comment]
As discussed on the community call, we're dropping bazel as an way of building cortex.
