### ISSUE TITLE
Users have no way of detecting 429

### ISSUE THREAD

**Issue by jml** [weaveworks/cortex#514]
I was just speaking with a user of Weave Cloud's Cortex. On our side, we see that their instance is getting a lot of 429 errors. On their side, there's no indication at all that this is the case.

**Comment by rade** [comment]
The lack of error logging on remote_write failures is a prometheus problem. I am quite sure @juliusv  is aware of this, and I thought it actually had been fixed.

**Comment by tomwilkie** [comment]
It has been fixed: https://github.com/prometheus/prometheus/pull/2786

**Comment by jml** [comment]
Thanks @tomwilkie! Just found that the hard way.
