### ISSUE TITLE
ditch memcache and maybe replace with DAX

### ISSUE THREAD

**Issue by rade** [weaveworks/cortex#517]
Now that we are storing chunks in DynamoDB instead of S3, it is questionable whether we still need memcache - one would hope that fetching chunks from DynamoDB is fast enough, and if it isn't then [DAX](https://aws.amazon.com/dynamodb/dax/) is probably a better alternative.

I suppose one question is whether we want to keep memcache around in order to speed up access to historical data predating the s3->dynamo switch.

**Comment by bboreham** [comment]
According to [the docs](http://docs.aws.amazon.com/amazondynamodb/latest/developerguide/DAX.client.html)

> At this time, DAX clients are available for Java and Node.js.

so this is not an option yet.

**Comment by bboreham** [comment]
Still not an option, and we have multiple back-ends and multiple caches now, so I don't think this issue is going anywhere.
