### ISSUE TITLE
Getting started requires non-trivial Prometheus knowledge

### ISSUE THREAD

**Issue by jml** [weaveworks/cortex#52]
We got some great feedback from a new user, @bboreham, who said:

> The Prometheus [Getting Started](https://prometheus.io/docs/introduction/getting_started/) page tells me to write a `prometheus.yml` file which is essentially identical to the one that came in the distribution (where "distribution" is the tarball provided at https://prometheus.io/download/)

and

> The [Configuration](https://prometheus.io/docs/operating/configuration/) page linked to in the cortex README is too complicated; not suitable for "getting started".

(I've paraphrased for context, adding links as appropriate).

Given that we hope to provide something useful to people without deep Prometheus expertise, we should think about how we can provide a smoother initial experience who are unfamiliar with it.

One possible solution would be to provide a container with some preset configuration.

**Comment by tomwilkie** [comment]
This doesn't strike me as a bug

**Comment by bboreham** [comment]
This (as originally envisaged) has now been fixed in Weave Cloud.
