### ISSUE TITLE
Locally new rules do not get evaluated

### ISSUE THREAD

**Issue by aaron7** [weaveworks/cortex#536]
Running cortex lite locally. I haven't confirmed if this is happening with other configurations.

After setting up the alert manager config and adding 8 rules, I see:
`time="2017-08-09T13:02:26Z" level=debug msg="Evaluating 8 rules..." orgID=1 source="ruler.go:244"` and the rules are evaluated.

After adding a new rule (copied and pasted from an existing rule and changing the name), I see:
`time="2017-08-09T13:02:27Z" level=debug msg="Adding 1 configurations" source="scheduler.go:179"`

However the logs still show only 8 rules are evaluated. Querying the new rule also returns no data. Only after restarting the ruler, the new rules are evaluated.

**Comment by bboreham** [comment]
I suspect this could have been caused by #482
