### ISSUE TITLE
Full Bazel build

### ISSUE THREAD

**Issue by jml** [weaveworks/cortex#565]
My Bazel master plan.

- [ ] Build protobufs with Bazel (in-progress, see #564) 
- [ ] Run Bazel tests in CI
- [ ] Use Bazel to build & push Docker images in CI
- [ ] Make sure macOS and Linux developers can build Docker images using Bazel
- [ ] Remove Dockerized build stuff from Makefile

CC @tomwilkie @ianthehat

**Comment by tomwilkie** [comment]
As discussed on the community call, we're dropping bazel as an way of building cortex.
