### ISSUE TITLE
Expose metric for ingest rate

### ISSUE THREAD

**Issue by squaremo** [weaveworks/cortex#567]
Suggested in weaveworks/service-conf#1193. Will help to see if 1. it's unexpectedly high, and 2. outstripping the flush rate.

**Comment by tomwilkie** [comment]
Its already there: `sum(rate(cortex_distributor_received_samples_total[1m])) by (job)`

**Comment by squaremo** [comment]
Then we just need to chuck it in the dashboard -- thanks Tom

**Comment by bboreham** [comment]
_sample_ arrival rate is a different dimension to _chunk_ flush rate; you can't compare them.
I agree it would be good to have a counter for chunk creation.
