### ISSUE TITLE
Copying YAML from Alertmanager config text area loses all leading whitespace

### ISSUE THREAD

**Issue by juliusv** [weaveworks/cortex#585]
When Ctrl-C copying the YAML config from https://frontend.dev.weave.works/org/proud-wind-05/alerting/receivers and pasting it into an editor, all leading whitespace is gone.

It should be possible to copy&paste this without breaking the content.

**Comment by rade** [comment]
cc @aaron7

**Comment by juliusv** [comment]
Oh wait, I should have filed this in the UI repo. Closing here.
