### ISSUE TITLE
Alert messages come through without a message body

### ISSUE THREAD

**Issue by jpellizzari** [weaveworks/cortex#601]
Messages to Slack and email are coming through without any text:
<img width="680" alt="screen shot 2017-11-17 at 10 09 53 am" src="https://user-images.githubusercontent.com/2802257/32963572-4563415e-cb85-11e7-9d3b-591e26d6ab5a.png">

Last known good message (note the timestamp):
<img width="466" alt="screen shot 2017-11-17 at 10 16 42 am" src="https://user-images.githubusercontent.com/2802257/32963581-4e14cfd4-cb85-11e7-875a-d673a0f0abc1.png">

From the events database:
```
{
  "browser": {
    "type": "monitor",
    "text": "",
    "attachments": [
      {
        "fallback": "[FIRING:41] ScrapeFailed (warning) | /api/prom/alertman\nager/#/alerts?receiver=fallback",
        "text": "\n",
        "color": "danger",
        "mrkdwn_in": [
          "fallback",
          "pretext",
          "text"
        ]
      }
    ],
    "timestamp": "2017-11-03T20:52:\n52.290691285Z"
  },
  "email": {
    "subject": "monitor",
    "body": ""
  },
  "slack": {
    "username": "AlertManager",
    "attachments": [
      {
        "title": "[FIRING:41] ScrapeFa\niled (warning)",
        "title_link": "/api/prom/alertmanager/#/alerts?receiver=fallback",
        "text": "\n",
        "fallback": "[FIRING:41] ScrapeFailed (warni\nng) | /api/prom/alertmanager/#/alerts?receiver=fallback",
        "color": "danger",
        "mrkdwn_in": [
          "fallback",
          "pretext",
          "text"
        ]
      }
    ]
  }
}
```

^ The slack.attachments[0].text field should have some text in it. Same with email.body.

Possibly related: 
https://github.com/weaveworks/notification/pull/117

https://github.com/weaveworks/cortex/commit/d714b622296ee32a85648480b59f8cc54793c263#diff-687f7844641224cb5825b565a83d58b5

**Comment by juliusv** [comment]
From chat: this customer does not have a receiver config (Alertmanager config) set, so I assume they are using the default config, which is currently:

```yml
route:
  receiver: fallback
receivers:
- name: fallback
  slack_configs:
  - api_url: internal://monitor
    text: |
      {{ .CommonAnnotations.summary }}
      {{ .CommonAnnotations.description }}
```

But their alerting rules do often not include a `description` field at all, and while `summary` is included everywhere, that field interpolates detail about the specific alert element (like `{{$labels.node}}`), which means that it will differ between multiple active alerts resulting from the same alerting rule. The result is that this field will no longer be part of `.CommonAnnotations`, since it's no longer common.

One would either have to print only `.CommonAnnotations` fields that are the same between alert elements, or iterate over all individual alert elements and print their details, like in this example:

https://github.com/prometheus/alertmanager/blob/master/template/default.tmpl#L7-L12

**Comment by jpellizzari** [comment]
Detailed reproduction steps:

1. Start a k8s cluster with an instrumented deployment. Set the number of replicas to 2 or more.
2. Define two alerting rules to trigger on the presence of the timeseries with mismatching label tokens, like so (notice that the summaries are different):
```
# Recording rules
ALERT ServiceDown3
 IF          up{job="default/string-reverse"}
 FOR         30s
 LABELS      { severity="critical" }
 ANNOTATIONS {
   summary = "Jordan testing in Weave Cloud Dev.",
   impact = "just testing",
   description = "Testing notifications",
 }

# Recording rules
ALERT ServiceDownOther3
 IF          up{job="default/string-reverse"}
 FOR         30s
 LABELS      { severity="critical" }
 ANNOTATIONS {
   summary = "Jordan testing in Weave Cloud Dev. Instance: {{$labels.instance}}",
   impact = "just testing",
   description = "Testing notifications",
 }
```
3. The result is a message that comes through without a summary:
![screen shot 2017-11-17 at 12 19 09 pm](https://user-images.githubusercontent.com/2802257/32967190-8a669c22-cb91-11e7-9e63-e7e6939bba0c.png)

**Comment by jpellizzari** [comment]
Related: 
https://github.com/weaveworks/service-conf/issues/1403
https://github.com/weaveworks/service-conf/issues/1051

**Comment by bboreham** [comment]
Can I suggest this Cortex issue should be closed, since it is more of a misunderstanding how to write alerts and templates.
