### ISSUE TITLE
Frequently getting errors when querying cortex

### ISSUE THREAD

**Issue by jml** [weaveworks/cortex#61]
On Weave Cloud dev & prod, getting:

```
Error executing query: too few successful reads, last error was: <nil>
```

when executing queries.

I haven't had a chance to investigate, but my guess is that deployments no longer visibly break the cluster (per #19) but they do silently break it, partly because we're not yet alerting on 500s for cortex at weaveworks (c.f. weaveworks/service#904).

This is probably something that will be fixed by clean shut-downs (which, at weaveworks, are blocked on weaveworks/service-conf#111), but I wanted to track something something symptom-oriented so I could have something to search for and also make notes on other things I found along the way.

Debugging this would be made easier by addressing #57, #58, #59, and #60.

**Comment by jml** [comment]
https://github.com/weaveworks/cortex/commit/c891ab57552bd72d5a8af551236f82d3b3dfb69d might help a bit too.

**Comment by jml** [comment]
weaveworks/service-conf#111 is fixed, but we're still not getting clean shutdowns. We're instrumenting more & getting better logging, and experimenting with extending the grace period.

**Comment by jml** [comment]
Error is now: 

```
Error executing query: could only find 1 ingesters for query. Need at least 2
```

**Comment by tomwilkie** [comment]
Monitoring in place to catch this in the future.

Work to fix it is being tracked in #87

**Comment by jml** [comment]
A whole bunch of people had pinged me about this problem & I've been directing them here to fix it. Think we should have kept this open until the problem it describes is actually fixed.

**Comment by tomwilkie** [comment]
Shall we direct them to #87?  Or close #87?  No point in having two issues for the same thing.

**Comment by tomwilkie** [comment]
Shall we direct them to #87?  Or close #87?  No point in having two issues for the same thing.

**Comment by tomwilkie** [comment]
Shall we direct them to #87?  Or close #87?  No point in having two issues for the same thing.

**Comment by tomwilkie** [comment]
Shall we direct them to #87?  Or close #87?  No point in having two issues for the same thing.

**Comment by tomwilkie** [comment]
Shall we direct them to #87?  Or close #87?  No point in having two issues for the same thing.

**Comment by tomwilkie** [comment]
Shall we direct them to #87?  Or close #87?  No point in having two issues for the same thing.

**Comment by jml** [comment]
Well, I think it *is* worth having separate things for symptom & cause, but I don't care super deeply about it. Let's direct to #87 (which I've added to the milestone). I'll paste the error message there too.

**Comment by tomwilkie** [comment]
Reopened at fixing #87 hasn't fixed the whole thing.

We're looking into ways of forcing k8s to do a one-at-a-time upgrade of the ingesters view readiness hooks.

**Comment by tomwilkie** [comment]
With bug fixes yesterday, we no longer get 500s during the rollout.
