### ISSUE TITLE
Querier may miss in-memory chunks when increasing the number of ingesters

### ISSUE THREAD

**Issue by aaron7** [weaveworks/cortex#613]
For example:

Let's say there are 5 ingesters, and the distributor is currently sending series A to 1, 2 & 3.

When we add another ingester (ingester 4), it takes ownership of some of the tokens. Series A may now be sent to 1, 2 and 4, with ingester 3 having a partial chunk in memory.

The querier also uses the ring. When querying in-memory chunks, it would only query ingesters 1, 2 and 4, missing out the partial chunk in ingester 3.

**Comment by tomwilkie** [comment]
This is correct, but shouldn't be a big problem as every sample is replicated at least twice.  Quorum reads will therefore always catch one of the replicas of the sample / series.

That being, this is where the "only add one node per 12hrs" restriction comes from, as adding two nodes quickly will mean a query could miss a sample.  Solution is to do some streaming on node adds, and not just node removes as we currently do.  I think I've got a branch somewhere that does this...

**Comment by bboreham** [comment]
Closed because it was never a problem, as you described.
