### ISSUE TITLE
Create benchmarks for chunk handling

### ISSUE THREAD

**Issue by bboreham** [weaveworks/cortex#627]
Part of #624 

Since it is complex to profile Cortex in-vivo, we should have benchmarks to demonstrate progress.
* serialising and deserialising chunks
* sort and de-dupe thousands of chunks

**Comment by bboreham** [comment]
Mostly covered by #628 #633

**Comment by tomwilkie** [comment]
#713 has a PromQL-to-inmemory-chunk benchmark covering this too.

**Comment by tomwilkie** [comment]
Propose we can close this?  Plenty of benchmarks now.
