### ISSUE TITLE
Unknown Function error for drop_common_labels()

### ISSUE THREAD

**Issue by khaines** [weaveworks/cortex#678]
With the latest code from the master branch (commit 73a2946), I noticed the  `drop_common_labels()` method no longer works.

The querier instance returns the following error:

`{
  "status": "error",
  "errorType": "bad_data",
  "error": "parse error at char 19: unknown function with name \"drop_common_labels\"",
  "message": "parse error at char 19: unknown function with name \"drop_common_labels\""
}`

This appears true for any expression, such as `drop_common_labels(up)`

**Comment by tomwilkie** [comment]
This was dropped in Prometheus 2.0, which Cortex is tracking now: https://prometheus.io/docs/prometheus/latest/migration/#promql

**Comment by khaines** [comment]
Thank you Tom. I forgot that detail from the migration guide.
