### ISSUE TITLE
ring_ingester_ownership metric does not set to zero when process exits

### ISSUE THREAD

**Issue by bboreham** [weaveworks/cortex#745]
So it hangs around for the 'stale' time (default 5 minutes) which gives a confusing picture.

The only thing I can think of to improve this is to have the leaving ingester hang around for 30 seconds after it has finished transferring chunks so the zero value is collected.

**Comment by tomwilkie** [comment]
This is fixed in Prometheus 2.0 (https://promcon.io/2017-munich/slides/staleness-in-prometheus-2-0.pdf) - it no longer waits 5 mins, as soon as the target disappears the timeseries should also stop.

**Comment by bboreham** [comment]
Does it push that NaN over `remote_write` ?

**Comment by tomwilkie** [comment]
It should do, but I suspect we don't test this e2e and there a fair chance something doesn't work on Cortex side.

**Comment by bcotton** [comment]
FWIW, we can confirm that the stale marker NaNs are pushed from Prometheus over remote write and Cortex does the right thing with them.

We are generating series from one of our components which we are pushing directly to the distributor. As we are not using Prometheus to gather these metrics, we had to include the stale marker NaNs in the stream when the series terminated. All works as expected.

**Comment by bboreham** [comment]
Closing as not a Cortex issue
