### ISSUE TITLE
Missing parameter to set query staleness time window

### ISSUE THREAD

**Issue by rsteneteg** [weaveworks/cortex#820]
The prometheus query engine considers time samples stale and ignores the whole time series if no datapoint has been received within the last 5m (default). If samples is scaped with more than 5m in between the querier will not always return data depending on how long ago the last datapoint came in.

Prometheus has a parameter for changing this time window --query.lookback-delta, but Cortex does not as that part of the prometheus code is not used.

In our use case we have seperate scrape jobs for a long vs short retention period, the long one scrapes at 15m intervals which causes the querier to only return data for 5m after each scrape, for the remaining 10m it returns no data.

I have a change for add this parameter to Cortex that I plan to push upstream

**Comment by bboreham** [comment]
Fixed by #821
