### ISSUE TITLE
Better monitoring for chunk state

### ISSUE THREAD

**Issue by jml** [weaveworks/cortex#84]
As part of understanding & fixing #61 and making sure it doesn't happen again, we want to gather data on:

- [ ] how big the backlog of flushes for chunks
- [x] (maybe) how many chunks there are in the system
- [ ] how many chunks we're dropping

**Comment by juliusv** [comment]
> (maybe) how many chunks there are in the system

That's just `cortex_ingester_memory_chunks`.

> how many chunks we're dropping

That's `rate(cortex_ingester_chunk_store_failures_total[1m])`. During normal operation, failed stores are simply retried infinitely, but during shutdown, it's a one-shot thing.

**Comment by tomwilkie** [comment]
> how big the backlog of flushes for chunks

Backlog can be inferred from the various metrics now.
