### ISSUE TITLE
Per-User metrics

### ISSUE THREAD

**Issue by gouthamve** [weaveworks/cortex#849]
As I start doing ops for Cortex, I'm wanting to have per-user metrics. Like the churn of their series, the samples per second per user, the active series per user, **the histogram of queries per user**, etc.

I understand we have a status page to lookup active series and samples per second, but that looks like it's just a hack around not having actual metrics we can alert on. 

I understand that the argument against adding per-user metrics is the high-cardinality, but even a small user exposes atleast 10K metrics and we'll be barely be adding like 30 metrics per user which is a very small percentage of the overall metrics to even matter.

I'm curious to know the thoughts on adding per-user metrics.

**Comment by bboreham** [comment]
Somewhat related: #577

As an administrator, I want this feature too. 

I see two practical considerations: authorisation to access data from other users/instances, and performance.

**Comment by gouthamve** [comment]
Auth for user-data: This would be metrics being exposed by cortex components (ingesters, distributors, queriers), as admins, we would naturally have access to those. Further, this is non-application data and the data about how cortex behaves and the amount of data being sent to us, pretty sure the customers want us to have it :)

Performance: I see you, I can see the queriers blow up with a histogram describing the query latency, but ingesters and distributors should be fine with around ~5metrics per user? We would be using `CounterVec`s to track these metrics and there would be no locking involved, hence I don't think there would be much of a performance issue there. For the queriers we can enable it using a flag, because we could either have a large number of small customers or a small number of large customers, for the latter, it makes a lot of sense.

**Comment by bboreham** [comment]
Ah, I suspect we are slightly talking across each other.
I am thinking in terms of taking metrics that are in each user's instance and making them available en mass to an administrator.
You are thinking of exposing new metrics, which may duplicate some within user's metrics, on Cortex itself.

Right?

**Comment by bboreham** [comment]
Previous [Slack conversation](https://weave-community.slack.com/archives/C4C2CVBUL/p1527847670000099):

**bboreham** as a Cortex administrator I want to do queries across multiple tenants.  Like "tell me the Prometheus remote send samples/sec and queue length for each tenant"
and "tell me the Prometheus ram size for each tenant"

**tom** And the tentant ID could be exposed as a label…
that’d be cool

**bboreham**  suspect the locking strategy inside ingesters might need care

**tom** also, there is no list of users anywhere - you could use all the users with chunks in the ingesters, but that could miss people who haven’t sent anything in ~15mins

**bboreham** [...] for many admin purposes, “active users” is fine.

**Comment by khaines** [comment]
I think there are two issues here and perhaps should be broken out. 

1 - cortex metrics by orgID, for purposes of graphing/alerting/troubleshooting/etc as an operator of cortex
2 - Being able to retrieve data across N orgIDs  (1<=N<=ALL)

I think they are both excellent items, if I've understood the conversation here :)

**Comment by csmarchbanks** [comment]
Mentioned in the call this morning was: https://github.com/weaveworks/cortex/issues/577

We could add some metrics to each customer's tenant, then query across those to get per customer data.

**Comment by bboreham** [comment]
This example came up today: I'd like to look at `prometheus_remote_storage_shards` across tenants - see what the typical range is, look for outliers.

**Comment by tomwilkie** [comment]
> Should we make things like cortex_discarded_samples_total per-tennant ?

Yes! /cc @jtlisi who wants to work on this.

**Comment by tomwilkie** [comment]
@jtlisi is `sum by (user, namespace) (cortex_ingester_memory_series_created_total) - 
sum by (user, namespace) (cortex_ingester_memory_series_removed_total)` the recommended way of getting number of timeseries per user?  Or should we also split `cortex_ingester_memory_series` by user name.

**Comment by tomwilkie** [comment]
The `cortex_ingester_memory_series_created_total - cortex_ingester_memory_series_removed_total` seems to be working well, this can be closed.
