### ISSUE TITLE
Investigate and fix 500s when writing to Dynamo

### ISSUE THREAD

**Issue by jml** [weaveworks/cortex#85]
We are getting a fairly constant stream of 500s from Dynamo when we attempt to write to it (~3-4qps on dev). 

We should understand what's causing this & fix it. https://github.com/weaveworks/monitoring/issues/12 will help.

**Comment by jml** [comment]
Might be related to #61, but too early to say.

**Comment by tomwilkie** [comment]
According to loggly, 90% of the log lines (and therefore errors) are ProvisionedThroughputExceededException.

**Comment by tomwilkie** [comment]
Write capacity was set to 400/s, which we're almost always trying to do more.  Tuning chunk size (#11) should help, but in the mean time I'll make it 1k/s.

**Comment by tomwilkie** [comment]
That seems to have had a small temporary reduction, but then back to usual - we're still being throttled.  I suspect we're just trying to write to much, and the change in provisioned capacity just reset some throttling counter.

**Comment by tomwilkie** [comment]
Now the ongoing deployment is done, the number of 500s has dropped dramatically (and the dynamodb latency is much improved).  So this did have an effect:

<img width="845" alt="screen shot 2016-11-06 at 06 32 00" src="https://cloud.githubusercontent.com/assets/444037/20038566/c26a8540-a3ea-11e6-86a5-9f42855f62fa.png">

**Comment by tomwilkie** [comment]
Fixed by #85
