### ISSUE TITLE
The cortex ingestion user stats don't consider replication factor

### ISSUE THREAD

**Issue by gouthamve** [weaveworks/cortex#868]
I was a bit surprised to know that the `/all_user_stats` reports the ingestion rate without considering the replication factor. Basically we show 3x the ingestion rate and active series for each user.

I understand the motivation but, because it is per-user stats, I think it makes sense to account for the replication factor in the stats page. WDYT?

**Comment by tomwilkie** [comment]
Yes!  We should at least make it clear on the page that they don't (or do, if we change them).

**Comment by bboreham** [comment]
If I recall, it got complicated when I considered the case that one ingester has just restarted, or not all ingesters responded. 

I went with the simplest thing that gave a qualitative view of what’s going on, which was an improvement on knowing nothing. 

Feel free to improve it.
