### ISSUE TITLE
Retriever config for Kubernetes that doesn't hardcode secret

### ISSUE THREAD

**Issue by jml** [weaveworks/cortex#88]
A couple of times over the last few days I've been pinged by people who have been confused by the cortex retrieval example in the [sockshop](https://github.com/microservices-demo/microservices-demo/), which [hardcodes a dummy, broken value](https://github.com/microservices-demo/microservices-demo/blob/master/deploy/kubernetes/manifests-cortex/cortex-config.yaml#L14) for the Weave Cloud access token.

It might be nice, as part of Cortex or something else, to provide an image that takes the access token as a command line or environment variable, and a set of Kubernetes configurations that use that image rather than prometheus.

Pro:
- easier onboarding for newcomers to prometheus

Con:
- masks the fact that retrievers really are vanilla prometheus
- maybe makes our messaging more confusing for existing prometheus users

**Comment by bboreham** [comment]
Fixed by https://github.com/microservices-demo/microservices-demo/pull/385 and the Launch Generator
