### ISSUE TITLE
Please update vendored copy of k8s.io/client-go

### ISSUE THREAD

**Issue by dholbach** [weaveworks/cortex#904]
Our current copy of k8s.io/client-go uses juju/ratelimit which is LGPL3. Upstream moved away from this in kubernetes/client-go@acc5249 - it'd be good if we followed this change as well.

**Comment by dholbach** [comment]
(This was solved in `weave` in https://github.com/weaveworks/weave/pull/3366 as well.)

**Comment by csmarchbanks** [comment]
This will get fixed once https://github.com/weaveworks/cortex/pull/898 is merged

**Comment by dholbach** [comment]
Brilliant - thanks for the update @csmarchbanks!

**Comment by tomwilkie** [comment]
Fixed by #898

**Comment by dholbach** [comment]
#898 is merged, closing this one as well.
