### ISSUE TITLE
Make ingester -> querier responses streaming

### ISSUE THREAD

**Issue by tomwilkie** [weaveworks/cortex#913]
We're seeing 200MB responses:

```
level=error ts=2018-07-31T19:53:37.7193191Z caller=engine.go:525 msg="error selecting series set" err="rpc error: code = ResourceExhausted desc = grpc: received message larger than 
max (200118416 vs. 67108864)"
```

Need to stream them.  Thanos already does this, maybe this can be a chance to unify the API? https://github.com/improbable-eng/thanos/blob/master/pkg/store/storepb/rpc.proto#L18

**Comment by bboreham** [comment]
How about pre-summarising the result before sending?  E.g. if the query is `sum` or `count`

**Comment by tomwilkie** [comment]
That would be great, but I don't know how to do it!
