### ISSUE TITLE
Had multiple ingesters with 0 tokens.

### ISSUE THREAD

**Issue by tomwilkie** [weaveworks/cortex#954]
We got into a state where we had multiple ingesters with 0 tokens; we don't quite know how.  Worse, its "viral" - when deleted those ingesters and new ones started, they were also given 0 tokens.

Related to #663 I think.

**Comment by cboggs** [comment]
We've seen this once before as well. Had to delete the entire consul ring key to get back to a working state.

**Comment by tomwilkie** [comment]
Should have put that here too:

> We don't know how we got in this state initially, but I suspect it was caused by an ingester being killed quickly - it started a transfer, but didn't actually get a chance to send any series. This triggered the EOF break, and the new ingester joined the ring with 0 tokens.
